name = "realtime-trends-crawler"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Cron trigger for every 10 minutes
[triggers]
crons = ["*/10 * * * *"]

# Build configuration
[build]
command = ""

[observability.logs]
enabled = true