name = "realtime-trends-data-worker"
main = "src/worker.js"
compatibility_date = "2024-10-08"

# Cron trigger for every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# Environment variables
[vars]
DATA_REPO = "realtime-trends/realtime-trends-extension-react"
DATA_BRANCH = "data"

# Secrets (set via wrangler secret put)
# GitHub App (Recommended - Most Secure):
# APP_ID = "123456"
# PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----"
# INSTALLATION_ID = "12345678"
#
# Fallback - Personal Access Token:
# GITHUB_TOKEN = "github_pat_11A..." (fine-grained token preferred)

# No build needed - pure JavaScript ES modules

[observability.logs]
enabled = true