name = "realtime-trends-data-worker"
main = "src/worker.js"
compatibility_date = "2024-10-08"

# Cron trigger for every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# Environment variables
[vars]
DATA_REPO = "realtime-trends/realtime-trends-extension-react"
DATA_BRANCH = "data"

# Secret (set via wrangler secret put)
# GITHUB_TOKEN = "github_pat_11A..." (fine-grained token)

# No build needed - pure JavaScript ES modules

[observability.logs]
enabled = true