# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Update version variable
        run: echo "version=$(echo "${{ github.ref }}" | grep -oP '([0-9\.]+)')" >> $GITHUB_ENV

      - name: Update version on manifest
        run: sed -i "s/0.0.0/${{ env.version }}/g" public/manifest.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          cd dist
          zip -r ../realtime-trends.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: realtime-trends.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive zip file
        uses: actions/upload-artifact@v4
        with:
          name: realtime-trends
          path: ./dist