name: Archive to test

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: CI="" NODE_OPTIONS=--openssl-legacy-provider npm run build --if-present

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          cd build
          zip -r ../realtime-trends.zip *

      - name: Archive zip file
        uses: actions/upload-artifact@v2
        with:
          name: realtime-trends
          path: ./build
