name: Update Trends Data

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run trends crawler and update data repo
      run: node scripts/update-data-repo.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DATA_REPO: ${{ github.repository }}
        DATA_BRANCH: 'data'